FROM journald-2-cloudwatch

RUN apt-get update \
  && apt-get install --no-install-recommends -y python3-pip \
  && pip3 --no-cache-dir install '.[testing]' \
  && apt-get purge -y python3-pip \
  && apt-get autoremove -y --purge \
  && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["pytest", "-ocache_dir=/dev/null", "/jd2cw/tests", "-vv", "--cov=jd2cw", "--cov-report=term", "--cov-report=xml:/tmp/codecov/coverage.xml"]
